version: '2'
services:
  speaking-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: speaking-master
    command:
    ports:
      - 3093:3093
    volumes:
      - .:/app/speaking-master
